### PR TITLE
Make use of variation selector-16 emojis

### PR DESCRIPTION
**Pull request by thisisjvgrace**
#21  Rationale

Discord recently updated many of its default emojis to variation selector-16 format. This PR utilizes that emoji format.

## Summary of changes made

This PR makes use of new variation selector-16 emoji format.
They say, an image is worth thousand words. 
Screenshot_20201003-192005_Discord

## Checklist

- [ ] This PR changes the jishaku module/cog codebase
    - [ ] These changes add new functionality to the module/cog
    - [ ] These changes fix an issue or bug in the module/cog
    - [x] I have tested that these changes work on a production bot instance
    - [ ] I have tested these changes against the CI/CD test suite
    - [ ] I have updated the documentation to reflect these changes
- [ ] This PR changes the CI/CD test suite
    - [ ] I have tested my suite changes are well-formed (all tests can be discovered)
    - [ ] These changes adjust existing test cases
    - [ ] These changes add new test cases
- [ ] This PR changes prose (such as the documentation, README or other Markdown/RST documents)
    - [x] I have proofread my changes for grammar and spelling issues
    - [x] I have tested that any changes regarding Markdown/RST syntax result in a well formed document

### CODE REVIEW

**Comment by iomintz** [comment]
Why was this PR closed?

**Comment by thisisjvgrace** [comment]
> Why was this PR closed?

because all the tests were failing and I wasn't even able to figure out why.

**Comment by iomintz** [comment]
Then leave it open and ask why. To find out yourself, click on the "X" and click on any of the "details" links. It looks like you forgot to update the test cases. [`test_paginator_interface`](https://github.com/Gorialis/jishaku/blob/f84938aa36cf97339499616fe9f699ff01a8a113/tests/test_paginator.py#L80) is failing because it's expecting the old emojis.

**Comment by iomintz** [comment]
Make sure to test it against the CI/CD test suite by running the same commands it does, namely 

```
pip install -Ur requirements/_.txt -r requirements/docs.txt -r requirements/test.txt
pip install -U "astroid @ git+https://github.com/PyCQA/astroid@master" "pylint @ git+https://github.com/PyCQA/pylint@master"
pytest -vs --cov=jishaku --cov-report term-missing:skip-covered
flake8 .
pylint jishaku
isort . --check-only --recursive
```

That way you can see if anything fails before you push.

**Pull request closed without merging**
